name: canteen_app
description: Mura-Mura Canteen POS mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For sending HTTP requests to your PHP API
  http: ^1.2.0

  # For saving login info on the phone so user stays logged in
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true